language: erlang

notifications:
  email: false

otp_release:
  - 18.1
  - 17.4

script:
  - make vsn-check
  - make eunit
  - make clean
  - rebar compile
  - make clean
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod 755 rebar3
  - ./rebar3 compile

